### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by AliGhahraei** [haydenflinner/magicinvoke#4]
Hi! 

Thank you for this cool Invoke extesion! I started using it today and ran into a small problem after installing it in a new virtualenv and running `invoke` without arguments:

```
Traceback (most recent call last):
  File "/home/ali/downloads/test/venv/bin/invoke", line 5, in <module>
    from invoke.main import program
  File "/home/ali/downloads/test/venv/lib/python3.9/site-packages/invoke/__init__.py", line 2, in <module>
    from .collection import Collection  # noqa
  File "/home/ali/downloads/test/venv/lib/python3.9/site-packages/invoke/collection.py", line 4, in <module>
    from .util import six, Lexicon, helpline
  File "/home/ali/downloads/test/venv/lib/python3.9/site-packages/invoke/util.py", line 39, in <module>
    from six import raise_from, iteritems  # noqa
ModuleNotFoundError: No module named 'six'
```

It worked after I manually installed the six package. I found a vendored six [here](https://github.com/haydenflinner/magicinvoke/blob/master/invoke/vendor/six.py), but I don't know if that's what was supposed to be found by Magicinvoke. The [Get Started](https://magicinvoke.readthedocs.io/en/latest/index.html#get-started) section only suggests `pip install magicinvoke`, so I'm guessing it should have worked with just that (but please correct me if I'm mistaken).

Here's my system information:
```
$ python --version
Python 3.9.2

$ pip --version
pip 21.0.1 from /home/ali/downloads/test/venv/lib/python3.9/site-packages/pip (python 3.9)

$ easy_install --version
setuptools 49.2.1 from /home/ali/downloads/test/venv/lib/python3.9/site-packages (Python 3.9)

$ uname -a
ali 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux
```

Update: I get the same error with Python 3.6.13

**Comment by haydenflinner** [comment]
I appreciate your trying to use the module! It still installs fine for me on a few machines, so I'm not sure what could be going on here, but I suspect I might already have six through some other means (I have a weird environment on the machines that I use this from).

https://github.com/haydenflinner/magicinvoke/blob/master/invoke/util.py#L34

You could add some logging to this line, logging the ImportError and maybe your sys.path. If it looks like something which is too tricky to fix in a pull request, I also wouldn't mind a PR deleting six from the vendor folder and adding six as a requirement to setup.py's "deps" list. Hopefully the module does not otherwise give you issues :-)

**Comment by haydenflinner** [comment]
For some reason this happened to me when I tried to install on Windows. Perhaps it's a problem with the most recent Python versions, 3.9+? Anyways, fixed with the latest patch on master. Am currently trying to release.
